export const refs = {
  gallery: document.querySelector('.gallery'),
  paginationList: document.querySelector('.pagination'),
  paginationBtnList: document.querySelector('.pagination__list'),
  firstPaginationBtn: document.querySelector('#first-btn'),
  lastPaginationBtn: document.querySelector('#last-btn'),
  previousArrow: document.querySelector('.js-previous'),
  nextArrow: document.querySelector('.js-next'),
  paginationRightDots: document.querySelector('.js-right-dots'),
  paginationLeftDots: document.querySelector('.js-left-dots'),
  filmsEl: document.querySelector('.films'),
  trailerBtn: document.querySelector('.trailer__btn'),
  trailerBox: document.querySelector('.trailer__box'),
  trailerBackdrop: document.querySelector('.trailer__backdrop'),
  trailerBtnClose: document.querySelector('.trailer__btn-close'),
  headerForm: document.querySelector('.header-form__search'),
  addRemoveWatchedQueueBtn: document.querySelector(
    '.add-remove-watched-queue-js'
  ),
  openModalBtn: document.querySelector('[data-action="open-modal"]'),
  backdropForm: document.querySelector('.backdrop_form'),
  addWatchedBtn: document.querySelector('.add-watched-js'),
  addQueue: document.querySelector('.add-queue-js'),
  removeWatchedBtn: document.querySelector('.remove-watched-js'),
  removeQueue: document.querySelector('.remove-queue-js'),
  btnWatched: document.querySelector('.js-btnWatched'),
  btnQueue: document.querySelector('.js-btnQueue'),
};
